# Generated by Django 3.0.3 on 2021-07-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ImageField(upload_to='images/')),
                ('info', models.CharField(max_length=255)),
            ],
        ),
    ]
